name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Packages
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo.png"
  android_12:
    image: "assets/images/app_logo.png"