name: myapp
description: "A new Flutter project for Bahir Dar Superapp."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.0
  pdf: ^3.10.8
  printing: ^5.11.0
  
  # Firebase Packages
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2

  # Maps & GPS
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^13.0.0  # ðŸ’¡ I recommend 13.0.0 for stability, but 14 is okay too.
  
  # ðŸ”¥ REQUIRED NEW PACKAGE
  permission_handler: ^11.3.1

  # State & Logic
  provider: ^6.1.2
  url_launcher: ^6.3.2

  # Sound and Vibration
  audioplayers: ^6.0.0
  vibration: ^3.1.5

  # Icons and Formatting
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  image_picker: ^1.2.1
  firebase_storage: ^13.0.6
  http: ^1.6.0
  flutter_map_marker_cluster: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Adjusted to be safe
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png