name: myapp
description: "A new Flutter project for Bahir Dar Superapp."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase Packages
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.6.12

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # State & Logic
  provider: ^6.1.2
  url_launcher: ^6.3.2

  # NEW: Sound and Vibration for S22 Ultra
  audioplayers: ^6.1.0
  vibration: ^2.0.1

  # Icons and Formatting
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png